/*
 * Generates public/sw.js with a per-build VERSION stamped in.
 *
 * Why: browsers only install a new service worker when /sw.js differs
 * byte-for-byte from the installed copy. A hardcoded VERSION means every deploy
 * ships an identical sw.js, so home-screen PWAs (esp. iOS) never update. By
 * baking a unique build id into VERSION on each build, a new deploy always
 * produces a changed worker → the update flow in AppInit kicks in.
 *
 * The generated public/sw.js is gitignored (it's a build artifact); this script
 * is the source of truth for the worker.
 *
 * Runs as part of `npm run build` (before `next build`).
 */

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const buildId =
  process.env.VERCEL_GIT_COMMIT_SHA ||
  process.env.VERCEL_DEPLOYMENT_ID ||
  new Date().toISOString().replace(/[^0-9]/g, "");

const sw = `/*
 * RoadTrip Trivia — app-shell service worker.
 *
 * GENERATED by scripts/gen-sw.mjs — do not edit by hand; edit the generator.
 * VERSION is stamped per build so each deploy ships a byte-different worker,
 * which is what triggers the browser/iOS PWA to pick up the new version.
 *
 * Strategies:
 *   - navigations  → network-first, fall back to cached page (or "/")
 *   - /_next/static & assets → cache-first (content-hashed, immutable)
 *   - other GETs   → stale-while-revalidate
 */

const VERSION = ${JSON.stringify(buildId)};
const CACHE = "rtt-shell-" + VERSION;
const PRECACHE = ["/", "/explore", "/saved", "/manifest.webmanifest", "/icon.svg"];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((c) => Promise.allSettled(PRECACHE.map((u) => c.add(u))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // skip Supabase & other origins

  if (req.mode === "navigate") {
    event.respondWith(
      fetch(req)
        .then((res) => {
          cachePut(req, res.clone());
          return res;
        })
        .catch(() => caches.match(req).then((c) => c || caches.match("/"))),
    );
    return;
  }

  const isAsset =
    url.pathname.startsWith("/_next/static") ||
    /\\.(?:css|js|woff2?|png|svg|ico|jpe?g|webp)$/.test(url.pathname);

  if (isAsset) {
    event.respondWith(
      caches.match(req).then(
        (c) =>
          c ||
          fetch(req).then((res) => {
            cachePut(req, res.clone());
            return res;
          }),
      ),
    );
    return;
  }

  event.respondWith(
    caches.match(req).then((cached) => {
      const network = fetch(req)
        .then((res) => {
          cachePut(req, res.clone());
          return res;
        })
        .catch(() => cached);
      return cached || network;
    }),
  );
});

function cachePut(req, res) {
  if (!res || res.status !== 200 || res.type === "opaque") return;
  caches
    .open(CACHE)
    .then((c) => c.put(req, res))
    .catch(() => {});
}
`;

const outPath = join(dirname(fileURLToPath(import.meta.url)), "..", "public", "sw.js");
await writeFile(outPath, sw, "utf8");
console.log(`[gen-sw] wrote public/sw.js (VERSION=${buildId})`);
